
language: go
sudo: required

services:
  - docker

go:
  - 1.5
  - tip

install: make get-deps

script:
  - make build test
  - cd examples/hello_world ; ../../involucro greet
  - cd ../compile_and_run ; ../../involucro compile package run test

matrix:
  allow_failures:
    - go: tip
