
language: go
sudo: required

services:
  - docker

go: 1.5

install: make get-deps

script:
  - make build test
  - make -C integrationtest

deploy:
  provider: releases
  api_key:
    secure: PrPgs1iO97+mV/3MXdJ+3Njl8kGMU41luf4NWIM9Q+QUiua+oCJs+vS6YS3OKW4K8qqEy/vqF3CBiRoupZrt7K6ROF6O/mn48eOo/WfUAACGoxgvn/mmt6I1zeyoNRB6alFzvfi5G0t335f2VlSSlWcXlZHP80a9cWLUSeg4oFnphsoqEsHB/7sxSJVg+tY5+byI9qAYcBB8oehFJffEU7Go5mHieOElbcw4umkIZm+mq8rihzAvsFMz5aY21nk9HXfOTUKAVqlU8EbTr5e6KNOUInTJxAeZFm6SO8Ff5u6Uf3sNjP1bOCnH8h4YCrXkYKFrmyYU+dZuKeqummQaq6cTeq4Glb9JaUWFkOHMTBzu2x4M1tD5LamYfFMFjcwALITnY8CJq/3spqZ7tEcBpeehdfb7+jA45xKOGZvF5qh2qCqry5MnTBacdViHD+0NC0TmkMcF2RK93Zn//tIH+OpE3AgHvYO3W+ldWlwSLClUwNtEsniajqNvkmL9htB9QuziDr4ZUvtPSq87IyVQtReuYfYfMxp7bkgJ5KddmiHi8M6bWfAZGB9V4cdCq9/slxXO6KUm5qJN/bQj6NsCV9KEjJJ2Wo06lshMSiqSjr21FPsO9Bc/WvlNCZioazIUG3j2wnm4wp9c/zWLHvTkcTJ97Uh+7VHtWDYr7+17LwU=
  file: involucro
  on:
    tags: true
    repo: thriqon/involucro
